server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://localhost:8081
          predicates:
            - Path=/payments/** 
        - id: car
          uri: http://localhost:8082
          predicates:
            - Path=/cars/** 
        - id: reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/** 
        - id: message
          uri: http://localhost:8084
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://localhost:8085
          predicates:
            - Path= /roomviews/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://user06-payment:8080
          predicates:
            - Path=/payments/** 
        - id: car
          uri: http://user06-car:8080
          predicates:
            - Path=/cars/** 
        - id: reservation
          uri: http://user06-reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: message
          uri: http://user06-message:8080
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://user06-viewpage:8080
          predicates:
            - Path= /roomviews/**
        - id: frontend
          uri: http://user06-frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
